var nibrs_codes = [
{ 'code': '0110', 'category': 'Homicide', 'color': '#bd352b', 'description': 'Homicide - Criminal' },
{ 'code': '0120', 'category': 'Homicide', 'color': '#bd352b', 'description': 'Homicide - Negligence' },
{ 'code': '0200', 'category': 'Rape', 'color': '#cd14de', 'description': 'Rape' },
{ 'code': '0300', 'category': 'Robbery', 'color': '#92add9', 'description': 'Robbery' },
{ 'code': '0410', 'category': 'Aggravated Assault', 'color': '#bd352b', 'description': 'Aggravated Assault' },
{ 'code': '0420', 'category': 'Aggravated Assault', 'color': '#bd352b', 'description': 'Aggravated Assault With Sexual Motives' },
{ 'code': '0510', 'category': 'Burglary', 'color': '#3946bd', 'description': 'Burglary-Forcible Entry' },
{ 'code': '0520', 'category': 'Burglary', 'color': '#3946bd', 'description': 'Burglary-Non-Forced Entry' },
{ 'code': '0610', 'category': 'Larceny', 'color': '#327f25', 'description': 'Pocket Picking' },
{ 'code': '0620', 'category': 'Larceny', 'color': '#327f25', 'description': 'Purse Snatching' },
{ 'code': '0630', 'category': 'Shoplifting', 'color': '#327f25', 'description': 'Shoplifting' },
{ 'code': '0640', 'category': 'Burglary from MV', 'color': '#3bc923', 'description': 'Larceny from Motor Vehicle' },
{ 'code': '0650', 'category': 'Larceny', 'color': '#3946bd', 'description': 'Auto Parts and Accessories' },
{ 'code': '0660', 'category': 'Larceny', 'color': '#3946bd', 'description': 'Larceny from Buildings' },
{ 'code': '0670', 'category': 'Larceny', 'color': '#3946bd', 'description': 'Larceny from Coin Operated Devices' },
{ 'code': '0690', 'category': 'Larceny', 'color': '#327f25', 'description': 'All Other Larceny' },
{ 'code': '0710', 'category': 'MV Theft', 'color': '#3bc923', 'description': 'Motor Vehicle Theft of Automobile' },
{ 'code': '0720', 'category': 'MV Theft', 'color': '#3bc923', 'description': 'Motor Vehicle Theft of Truck' },
{ 'code': '0730', 'category': 'MV Theft', 'color': '#3bc923', 'description': 'Motor Vehicle Theft of Bus' },
{ 'code': '0740', 'category': 'MV Theft', 'color': '#3bc923', 'description': 'Motor Vehicle Theft of Recreation Vehicle' },
{ 'code': '0790', 'category': 'MV Theft', 'color': '#3bc923', 'description': 'Motor Vehicle Theft of All Other Vehicles' },
{ 'code': '0810', 'category': 'Assault', 'color': '#bd352b', 'description': 'Simple Physical Assault' },
{ 'code': '0820', 'category': 'Assault', 'color': '#bd352b', 'description': 'Simple Non-physical Threat, Intimidation' },
{ 'code': '0830', 'category': 'Assault', 'color': '#bd352b', 'description': 'Simple Physical Assault With Sexual Motive' },
{ 'code': '0840', 'category': 'Assault', 'color': '#bd352b', 'description': 'Simple Non-physical Assault With Sexual Motive' },
{ 'code': '0890', 'category': 'Assault', 'color': '#bd352b', 'description': 'All Other Simple Assault' },
{ 'code': '0900', 'category': 'Arson', 'color': '#fda203', 'description': 'Arson' }];

var other_codes = [
{ 'code': '1015', 'category': 'Theft Other', 'color': '#327f25', 'description': 'Forgery - Using/Uttering' },
{ 'code': '1024', 'category': 'Theft Other', 'color': '#327f25', 'description': 'Counterfeiting - Possessing/Concealing' },
{ 'code': '1026', 'category': 'Theft Other', 'color': '#327f25', 'description': 'Counterfeiting - Using' },
{ 'code': '1027', 'category': 'Theft Other', 'color': '#327f25', 'description': 'Counterfeiting - Undetermined/Not Applicable' },
{ 'code': '1000', 'category': 'Theft Other', 'color': '#327f25', 'description': 'Forgery - Counterfeiting' },
{ 'code': '1011', 'category': 'Theft Other', 'color': '#327f25', 'description': 'Forgery - Buying/Receiving' },
{ 'code': '1012', 'category': 'Theft Other', 'color': '#327f25', 'description': 'Forgery - Selling/Distributing' },
{ 'code': '1013', 'category': 'Theft Other', 'color': '#327f25', 'description': 'Forgery - Possessing/Concealing' },
{ 'code': '1014', 'category': 'Theft Other', 'color': '#327f25', 'description': 'Forgery - Transporting' },
{ 'code': '1016', 'category': 'Theft Other', 'color': '#327f25', 'description': 'Forgery - Undetermined/Not Applicable' },
{ 'code': '1021', 'category': 'Theft Other', 'color': '#327f25', 'description': 'Counterfeiting - Buying/Receiving' },
{ 'code': '1022', 'category': 'Theft Other', 'color': '#327f25', 'description': 'Counterfeiting - Manufacturing' },
{ 'code': '1023', 'category': 'Theft Other', 'color': '#327f25', 'description': 'Counterfeiting - Selling/Distributing' },
{ 'code': '1025', 'category': 'Theft Other', 'color': '#327f25', 'description': 'Counterfeiting - Transporting' },
{ 'code': '1120', 'category': 'Fraud', 'color': '#327f25', 'description': 'Obtaining Money/property By False Pretense' },
{ 'code': '1140', 'category': 'Fraud', 'color': '#327f25', 'description': 'Unauthorized Use Of Conveyance' },
{ 'code': '1150', 'category': 'Fraud', 'color': '#327f25', 'description': 'Credit Card/Automated Teller Machines' },
{ 'code': '1170', 'category': 'Fraud', 'color': '#327f25', 'description': 'Impersonation' },
{ 'code': '1190', 'category': 'Fraud', 'color': '#327f25', 'description': 'All Other Fraud' },
{ 'code': '1100', 'category': 'Fraud', 'color': '#327f25', 'description': 'Fraud' },
{ 'code': '1110', 'category': 'Fraud', 'color': '#327f25', 'description': 'Worthless Checks' },
{ 'code': '1130', 'category': 'Fraud', 'color': '#327f25', 'description': 'Confidence Games/Larceny By Trickery' },
{ 'code': '1160', 'category': 'Fraud', 'color': '#327f25', 'description': 'Welfare' },
{ 'code': '1180', 'category': 'Fraud', 'color': '#327f25', 'description': 'Fraud of Wire/Computer/Other Electronic Manipulation' },
{ 'code': '1290', 'category': 'Theft Other', 'color': '#327f25', 'description': 'All Other Embezzlement' },
{ 'code': '1200', 'category': 'Theft Other', 'color': '#327f25', 'description': 'Embezzlement' },
{ 'code': '1210', 'category': 'Theft Other', 'color': '#327f25', 'description': 'Via Paper' },
{ 'code': '1220', 'category': 'Theft Other', 'color': '#327f25', 'description': 'Embezzlement of Wire/Computer/Other Electronic Manipulation' },
{ 'code': '1330', 'category': 'Theft Other', 'color': '#327f25', 'description': 'Possessing/Concealing Stolen Property' },
{ 'code': '1300', 'category': 'Theft Other', 'color': '#327f25', 'description': 'Stolen Property' },
{ 'code': '1310', 'category': 'Theft Other', 'color': '#327f25', 'description': 'Buying/Receiving Stolen Property' },
{ 'code': '1320', 'category': 'Theft Other', 'color': '#327f25', 'description': 'Selling/Distributing Stolen Property' },
{ 'code': '1340', 'category': 'Theft Other', 'color': '#327f25', 'description': 'Transporting Stolen Property' },
{ 'code': '1400', 'category': 'Vandalism', 'color': '#737272', 'description': 'Criminal Damage To Property (Vandalism)' },
{ 'code': '1530', 'category': 'Weapons Violation', 'color': '#737272', 'description': 'Possessing/concealing Weapons' },
{ 'code': '1550', 'category': 'Weapons Violation', 'color': '#737272', 'description': 'Using Weapons (illegal Discharge)' },
{ 'code': '1590', 'category': 'Weapons Violation', 'color': '#737272', 'description': 'Other Weapons Violations' },
{ 'code': '1500', 'category': 'Weapons Violation', 'color': '#737272', 'description': 'Weapons Violations' },
{ 'code': '1510', 'category': 'Weapons Violation', 'color': '#737272', 'description': 'Buying/Receiving Weapons' },
{ 'code': '1520', 'category': 'Weapons Violation', 'color': '#737272', 'description': 'Selling/Distributing Weapons' },
{ 'code': '1540', 'category': 'Weapons Violation', 'color': '#737272', 'description': 'Transporting Weapons' },
{ 'code': '1610', 'category': 'Sex Offense Other', 'color': '#cd14de', 'description': 'Prostitution' },
{ 'code': '1600', 'category': 'Sex Offense Other', 'color': '#cd14de', 'description': 'Prostitution' },
{ 'code': '1620', 'category': 'Sex Offense Other', 'color': '#cd14de', 'description': 'Assisting/Promoting Commercialized Vice' },
{ 'code': '1730', 'category': 'Sex Offense Other', 'color': '#cd14de', 'description': 'Indecent Exposure' },
{ 'code': '1780', 'category': 'Sex Offense Other', 'color': '#cd14de', 'description': 'Child Molestation (non-assaultive)' },
{ 'code': '1790', 'category': 'Sex Offense Other', 'color': '#cd14de', 'description': 'All Other Sex Offenses' },
{ 'code': '1700', 'category': 'Sex Offense Other', 'color': '#cd14de', 'description': 'Sex Offenses' },
{ 'code': '1710', 'category': 'Sex Offense Other', 'color': '#cd14de', 'description': 'Peeping Tom' },
{ 'code': '1720', 'category': 'Sex Offense Other', 'color': '#cd14de', 'description': 'Sodomy (Crime Against Nature)' },
{ 'code': '1740', 'category': 'Sex Offense Other', 'color': '#cd14de', 'description': 'Incest (non-assaultive)' },
{ 'code': '1750', 'category': 'Sex Offense Other', 'color': '#cd14de', 'description': 'Male Rape' },
{ 'code': '1760', 'category': 'Sex Offense Other', 'color': '#cd14de', 'description': 'Sexual Assault With An Object' },
{ 'code': '1770', 'category': 'Sex Offense Other', 'color': '#cd14de', 'description': 'Statutory Rape (Under Age of 12)' },
{ 'code': '1810', 'category': 'Drug Narcotics Violation', 'color': '#6c3a75', 'description': 'Drug Violations' },
{ 'code': '1834', 'category': 'Drug Narcotics Violation', 'color': '#6c3a75', 'description': 'Equipment/paraphernalia - Possessing/concealing' },
{ 'code': '1890', 'category': 'Drug Narcotics Violation', 'color': '#6c3a75', 'description': 'All Other Drug Violations' },
{ 'code': '1800', 'category': 'Drug Narcotics Violation', 'color': '#6c3a75', 'description': 'Drug/Narcotic Offenses' },
{ 'code': '1820', 'category': 'Drug Narcotics Violation', 'color': '#6c3a75', 'description': 'False Representation Of Drugs' },
{ 'code': '1831', 'category': 'Drug Narcotics Violation', 'color': '#6c3a75', 'description': 'Equipment/paraphernalia - Buying' },
{ 'code': '1836', 'category': 'Drug Narcotics Violation', 'color': '#6c3a75', 'description': 'Equipment/paraphernalia - Using' },
{ 'code': '1832', 'category': 'Drug Narcotics Violation', 'color': '#6c3a75', 'description': 'Equipment/paraphernalia - Manufacturing' },
{ 'code': '1833', 'category': 'Drug Narcotics Violation', 'color': '#6c3a75', 'description': 'Equipment/paraphernalia - Selling' },
{ 'code': '1835', 'category': 'Drug Narcotics Violation', 'color': '#6c3a75', 'description': 'Equipment/paraphernalia - Transporting' },
{ 'code': '2010', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'Desertion/Abandonment' },
{ 'code': '2030', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'Child Neglect (non-assaultive)' },
{ 'code': '2040', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'Child Abuse (non-assaultive)' },
{ 'code': '2090', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'All Other Offenses Against Family' },
{ 'code': '2000', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'Offenses Against Family' },
{ 'code': '2020', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'Non-Support/Non-Payment of Alimony' },
{ 'code': '2100', 'category': 'DUI', 'color': '#6c3a75', 'description': 'DWI - Alcohol and/or Drugs' },

{ 'code': '1900', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'Gambling Offenses' },
{ 'code': '1920', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'Betting And Wagering' },
{ 'code': '1930', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'Operating/Promoting/Assisting' },
{ 'code': '1941', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'Equipment Violations - Buying' },
{ 'code': '1942', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'Equipment Violations - Manufacturing' },
{ 'code': '1943', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'Equipment Violations - Selling' },
{ 'code': '1944', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'Equipment Violations - Possessing/concealing' },
{ 'code': '1945', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'Equipment Violations - Transporting' },
{ 'code': '1946', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'Equipment Violations - Using' },
{ 'code': '1950', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'Sports Tampering' },
{ 'code': '1990', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'All Other' },
{ 'code': '2213', 'category': 'Alcohol Violation', 'color': '#6c3a75', 'description': 'Transporting - Tax Paid Liquor' },
{ 'code': '2220', 'category': 'Alcohol Violation', 'color': '#6c3a75', 'description': 'Buying/Receiving - Non-Tax Paid Liquor' },
{ 'code': '2221', 'category': 'Alcohol Violation', 'color': '#6c3a75', 'description': 'Selling/Distributing - Non-Tax Paid Liquor' },
{ 'code': '2222', 'category': 'Alcohol Violation', 'color': '#6c3a75', 'description': 'Possessing/Concealing - Non-Tax Paid Liquor' },
{ 'code': '2223', 'category': 'Alcohol Violation', 'color': '#6c3a75', 'description': 'Transporting - Non-Tax Paid Liquor' },
{ 'code': '2224', 'category': 'Alcohol Violation', 'color': '#6c3a75', 'description': 'Using/Consuming - Non-Tax Paid Liquor' },
{ 'code': '2225', 'category': 'Alcohol Violation', 'color': '#6c3a75', 'description': 'Manufacturing - Non-Tax Paid Liquor' },
{ 'code': '2230', 'category': 'Alcohol Violation', 'color': '#6c3a75', 'description': 'Illegal Sale To Minors' },
{ 'code': '2240', 'category': 'Alcohol Violation', 'color': '#6c3a75', 'description': 'Sale Outside Prescribed Hours' },
{ 'code': '2250', 'category': 'Alcohol Violation', 'color': '#6c3a75', 'description': 'Sale Without a License' },
{ 'code': '2214', 'category': 'Alcohol Violation', 'color': '#6c3a75', 'description': 'Using/Consuming - Tax Paid Liquor' },
{ 'code': '2290', 'category': 'Alcohol Violation', 'color': '#6c3a75', 'description': 'All Other Liquor Law Violations' },
{ 'code': '2200', 'category': 'Alcohol Violation', 'color': '#6c3a75', 'description': 'Liquor Law Violations' },
{ 'code': '2210', 'category': 'Alcohol Violation', 'color': '#6c3a75', 'description': 'Buying/Receiving - Tax Paid Liquor' },
{ 'code': '2211', 'category': 'Alcohol Violation', 'color': '#6c3a75', 'description': 'Selling/Distributing - Tax Paid Liquor' },
{ 'code': '2212', 'category': 'Alcohol Violation', 'color': '#6c3a75', 'description': 'Possessing/Concealing - Tax Paid Liquor' },
{ 'code': '2400', 'category': 'Disorderly Conduct', 'color': '#737272', 'description': 'Disorderly' },
{ 'code': '2420', 'category': 'Disorderly Conduct', 'color': '#737272', 'description': 'Disturbing The Peace' },
{ 'code': '2430', 'category': 'Disorderly Conduct', 'color': '#737272', 'description': 'Fighting (Affray)' },
{ 'code': '2440', 'category': 'Disorderly Conduct', 'color': '#737272', 'description': 'Unlawful Assembly' },
{ 'code': '2450', 'category': 'Disorderly Conduct', 'color': '#737272', 'description': 'Drunk And Disruptive' },
{ 'code': '2490', 'category': 'Disorderly Conduct', 'color': '#737272', 'description': 'All Other' },
{ 'code': '2410', 'category': 'Disorderly Conduct', 'color': '#737272', 'description': 'Disorderly Conduct' },
{ 'code': '2500', 'category': 'Sex Offense Other', 'color': '#cd14de', 'description': 'Obscene Material/Pornography' },
{ 'code': '2510', 'category': 'Sex Offense Other', 'color': '#cd14de', 'description': 'Buying/Receiving' },
{ 'code': '2520', 'category': 'Sex Offense Other', 'color': '#cd14de', 'description': 'Selling/Distributing' },
{ 'code': '2530', 'category': 'Sex Offense Other', 'color': '#cd14de', 'description': 'Possessing/Concealing' },
{ 'code': '2540', 'category': 'Sex Offense Other', 'color': '#cd14de', 'description': 'Transporting' },
{ 'code': '2550', 'category': 'Sex Offense Other', 'color': '#cd14de', 'description': 'Using' },
{ 'code': '2560', 'category': 'Sex Offense Other', 'color': '#cd14de', 'description': 'Publishing' },
{ 'code': '2570', 'category': 'Sex Offense Other', 'color': '#cd14de', 'description': 'Exploiting Children' },
{ 'code': '2580', 'category': 'Sex Offense Other', 'color': '#cd14de', 'description': 'Operating/Pormoting' },
{ 'code': '2590', 'category': 'Sex Offense Other', 'color': '#cd14de', 'description': 'All Other' },
{ 'code': '2600', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'All Other Offenses' },
{ 'code': '2610', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'Bigamy/Marriage Laws' },
{ 'code': '2630', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'Blackmail/Extortion' },
{ 'code': '2631', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'Bribery' },
{ 'code': '2620', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'Kidnapping' },
{ 'code': '2640', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'Contempt Of Court/Perjury/Court Violations' },
{ 'code': '2650', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'Escape From Custody Or Resist Arrest' },
{ 'code': '2660', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'Parole and Probation Violations' },
{ 'code': '2670', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'Trespassing' },
{ 'code': '2680', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'City Ordinance Violations' },
{ 'code': '2690', 'category': 'All Other Criminal Offenses', 'color': '#737272', 'description': 'All Other' },
{ 'code': '4000', 'category': 'All Other NonCriminal Offenses', 'color': '#c5c4c4', 'description': 'Additional Offense Categories' },
{ 'code': '4030', 'category': 'All Other NonCriminal Offenses', 'color': '#c5c4c4', 'description': 'Non-negligent Traffic Death' },
{ 'code': '4010', 'category': 'All Other NonCriminal Offenses', 'color': '#c5c4c4', 'description': 'All Traffic (except DWI)' },
{ 'code': '4020', 'category': 'All Other NonCriminal Offenses', 'color': '#c5c4c4', 'description': 'Suicide' },
{ 'code': '4040', 'category': 'All Other NonCriminal Offenses', 'color': '#c5c4c4', 'description': 'Non-criminal Detainment (Inv Committment)' },
{ 'code': '8010', 'category': 'All Other NonCriminal Offenses', 'color': '#c5c4c4', 'description': 'Missing Persons' },
{ 'code': '8011', 'category': 'All Other NonCriminal Offenses', 'color': '#c5c4c4', 'description': 'Runaway' },
{ 'code': '9999', 'category': 'All Other NonCriminal Offenses', 'color': '#c5c4c4', 'description': 'Registered Sex Offender' },
{ 'code': '9900', 'category': 'All Other NonCriminal Offenses', 'color': '#c5c4c4', 'description': 'User Defined' },
{ 'code': '9910', 'category': 'All Other NonCriminal Offenses', 'color': '#c5c4c4', 'description': 'Calls For Service' },
{ 'code': '9997', 'category': 'All Other NonCriminal Offenses', 'color': '#c5c4c4', 'description': 'Hit and Run Accidents' },
{ 'code': '9998', 'category': 'All Other NonCriminal Offenses', 'color': '#c5c4c4', 'description': 'Search Warrants'}];

var fi_codes = [
{ 'code': 'DP', 'category': 'DP', 'color': '#c5c4c4', 'description': 'DP' },
{ 'code': 'FI', 'category': 'FI', 'color': '#c5c4c4', 'description': 'FI' },
{ 'code': 'HV', 'category': 'HV', 'color': '#c5c4c4', 'description': 'HV' },
{ 'code': 'INV', 'category': 'INV', 'color': '#c5c4c4', 'description': 'INV' },
{ 'code': 'IX', 'category': 'IX', 'color': '#c5c4c4', 'description': 'IX' },
{ 'code': 'PW', 'category': 'PW', 'color': '#c5c4c4', 'description': 'PW'}];

var categoryColors = [
{ 'category': 'Aggravated Assault', 'color': '#bd352b' },
{ 'category': 'Assault Other', 'color': '#bd352b' },
{ 'category': 'Domestic Violence', 'color': '#bd352b' },
{ 'category': 'All Other NonCriminal Offenses', 'color': '#c5c4c4' },
{ 'category': 'All Other Criminal Offenses', 'color': '#737272' },
{ 'category': 'Disorderly Conduct', 'color': '#737272' },
{ 'category': 'Vandalism', 'color': '#737272' },
{ 'category': 'Weapons Violation', 'color': '#737272' },
{ 'category': 'Attempted Homicide', 'color': '#2a2a2a' },
{ 'category': 'Death Investigation', 'color': '#2a2a2a' },
{ 'category': 'Homicide', 'color': '#2a2a2a' },
{ 'category': 'Robbery Commercial', 'color': '#92add9' },
{ 'category': 'Robbery Individual', 'color': '#92add9' },
{ 'category': 'Burglary Commercial', 'color': '#3946bd' },
{ 'category': 'Burglary Residential', 'color': '#3946bd' },
{ 'category': 'Burglary from MV', 'color': '#3bc923' },
{ 'category': 'MV Theft', 'color': '#3bc923' },
{ 'category': 'Fraud', 'color': '#327f25' },
{ 'category': 'Shoplifting', 'color': '#327f25' },
{ 'category': 'Theft Other', 'color': '#327f25' },
{ 'category': 'Theft', 'color': '#327f25' },
{ 'category': 'Alcohol Violation', 'color': '#6c3a75' },
{ 'category': 'Drug Narcotics Violation', 'color': '#6c3a75' },
{ 'category': 'DUI', 'color': '#6c3a75' },
{ 'category': 'Traffic All', 'color': '#6c3a75' },
{ 'category': 'Sex Offense Other', 'color': '#cd14de' },
{ 'category': 'Sexual Assault', 'color': '#cd14de' },
{ 'category': 'Arson', 'color': '#fda203'}];
